### user1,2,3 checks alarm
GET http://localhost:8080/alarms/2


### user3 deletes one alarm
DELETE http://localhost:8080/delete/alarm
Content-Type: application/json

{
  "alarmEntityPKId" : 1,
  "alarmReceiveUserPKId" : 3
}



### user1 deletes all alarm
DELETE http://localhost:8080/delete/entire-alarms/1