### user1 sign up
POST http://localhost:8080/temp/signup
Content-Type: application/json
Accept: application/json

{
  "nickname": "one"
}


### user2 sign up
POST http://localhost:8080/temp/signup
Content-Type: application/json
Accept: application/json

{
  "nickname": "two"
}


### user3 sign up
POST http://localhost:8080/temp/signup
Content-Type: application/json
Accept: application/json

{
  "nickname": "three"
}



### user4 sign up
POST http://localhost:8080/temp/signup
Content-Type: application/json
Accept: application/json

{
  "nickname": "four"
}



### user3 follows user1,2 / user1 follows user2
POST http://localhost:8080/follow
Content-Type: application/json

{
    "followSentUserPKId": 3,
    "followReceivedUserPKId": 2
}



### check followees of user3
GET http://localhost:8080/followees/3



### check followers of user1,2
GET http://localhost:8080/followers/1



### user3 ufollows user1,2
DELETE http://localhost:8080/delete/follow-relation/2



### user3 search users by nickname containing "one";
GET http://localhost:8080/search/users/two