### user1 post publicTodo 1
POST http://localhost:8080/create/public/todo
Content-Type: application/json
Accept: application/json

{
  "authorUserPKId" : 4,
  "authorUserNickname" : "four",
  "publicTodoContent" : "develop Social Todo App BackEnd",
  "deadlineDate" : "2023-01-31"
}



### user1,2,3,4 post publicTodo 2
POST http://localhost:8080/create/public/todo
Content-Type: application/json
Accept: application/json

{
  "authorUserPKId" : 4,
  "authorUserNickname" : "four",
  "publicTodoContent" : "work2",
  "deadlineDate" : "2023-01-31"
}




### user2,3,4 press support/nag on publicTodo 1
PUT http://localhost:8080/create/nag
Content-Type: application/json

{
  "publicTodoPKId" : 1,
  "supportNagSentUserPKId" : 4
}



### user3 checks the support/nag pressed users
GET http://localhost:8080/nag/users/1?pageNumber=2




### user2,3,4 canceled support/nag
PUT http://localhost:8080/cancel/support
Content-Type: application/json

{
  "publicTodoPKId" : 1,
  "supportNagSentUserPKId" : 2
}





### user1 updates deadlineDate or finishes publicTodo 1 before deadlineDate
PUT localhost:8080/update/public/todo
Content-Type: application/json
Accept: application/json

{
  "publicTodoPKId": 7,
  "authorUserPKId": 4,
  "deadlineDate": "2023-01-08",
  "finished": true
}




### user1 deletes publicTodo 1 and 2
DELETE localhost:8080/delete/public/todo
Content-Type: application/json

{
  "publicTodoPKId": 2,
  "authorUserPKId": 1
 }




### user3 requested his/her timeline
GET http://localhost:8080/time-line/3?pageNumber=1

