spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/social_todo_backend
    username: 
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
