spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop # Need special concern on this option when deploying app on AWS, Heroku etc.
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
