spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/social_todo_backend
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

aws:
  redis:
    url:
    port: 6379

jwt:
  secret:
    key:
